# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(max_length=1000)),
                ('sent_to', models.CharField(max_length=1000)),
                ('sent_on', models.DateTimeField()),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('organizer_name', models.CharField(max_length=200)),
                ('organizer_contact', models.CharField(max_length=200)),
                ('organizer_mail', models.CharField(max_length=200)),
            ],
        ),
    ]
