# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(max_length=500)),
                ('sent_to', models.CharField(max_length=500)),
                ('sent_on', models.DateTimeField()),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
    ]
