# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tau.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_used', models.PositiveIntegerField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('filename', models.CharField(editable=False, max_length=500)),
                ('file', models.FileField(upload_to=tau.models.upload_to)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tau.Drive')),
            ],
        ),
    ]
