# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('full_path', models.TextField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='drive',
        ),
        migrations.AlterField(
            model_name='drive',
            name='space_used',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='folder',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tau.Drive'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tau.Folder'),
        ),
    ]
