# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tau.Drive'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
