# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tau.models


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0004_auto_20161207_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=500)),
                ('file', models.FileField(upload_to=tau.models.upload_to)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tau.Drive')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tau.Folder')),
            ],
        ),
    ]
